# These are supported funding model platforms

github: passariello
patreon: passariello
ko_fi: passariello
liberapay: passariello
issuehunt: passariello
custom:
 [
  "https://dario.passariello.ca",
  "https://www.indiegogo.com/individuals/28513718",
 ]
